// Mock data for all 114 Surahs of the Quran
export const MOCK_SURAHS = [
    { id: 1, number: 1, nameArabic: 'الفَاتِحَة', nameEnglish: 'Al-Fatihah', translation: 'The Opening', revelationType: 'Meccan', ayahCount: 7 },
    { id: 2, number: 2, nameArabic: 'البَقَرَة', nameEnglish: 'Al-Baqarah', translation: 'The Cow', revelationType: 'Medinan', ayahCount: 286 },
    { id: 3, number: 3, nameArabic: 'آل عِمۡرَان', nameEnglish: 'Ali Imran', translation: 'The Family of Imran', revelationType: 'Medinan', ayahCount: 200 },
    { id: 4, number: 4, nameArabic: 'النِّسَاء', nameEnglish: 'An-Nisa', translation: 'The Women', revelationType: 'Medinan', ayahCount: 176 },
    { id: 5, number: 5, nameArabic: 'المَائـِدَة', nameEnglish: 'Al-Maidah', translation: 'The Table Spread', revelationType: 'Medinan', ayahCount: 120 },
    { id: 6, number: 6, nameArabic: 'الأَنۡعَام', nameEnglish: 'Al-Anam', translation: 'The Cattle', revelationType: 'Meccan', ayahCount: 165 },
    { id: 7, number: 7, nameArabic: 'الأَعۡرَاف', nameEnglish: 'Al-Araf', translation: 'The Heights', revelationType: 'Meccan', ayahCount: 206 },
    { id: 8, number: 8, nameArabic: 'الأَنفَال', nameEnglish: 'Al-Anfal', translation: 'The Spoils of War', revelationType: 'Medinan', ayahCount: 75 },
    { id: 9, number: 9, nameArabic: 'التَّوۡبَة', nameEnglish: 'At-Tawbah', translation: 'The Repentance', revelationType: 'Medinan', ayahCount: 129 },
    { id: 10, number: 10, nameArabic: 'يُونُس', nameEnglish: 'Yunus', translation: 'Jonah', revelationType: 'Meccan', ayahCount: 109 },
    { id: 11, number: 11, nameArabic: 'هُود', nameEnglish: 'Hud', translation: 'Hud', revelationType: 'Meccan', ayahCount: 123 },
    { id: 12, number: 12, nameArabic: 'يُوسُف', nameEnglish: 'Yusuf', translation: 'Joseph', revelationType: 'Meccan', ayahCount: 111 },
    { id: 13, number: 13, nameArabic: 'الرَّعۡد', nameEnglish: 'Ar-Rad', translation: 'The Thunder', revelationType: 'Medinan', ayahCount: 43 },
    { id: 14, number: 14, nameArabic: 'إِبۡرَاهِيمَ', nameEnglish: 'Ibrahim', translation: 'Abraham', revelationType: 'Meccan', ayahCount: 52 },
    { id: 15, number: 15, nameArabic: 'الحِجۡر', nameEnglish: 'Al-Hijr', translation: 'The Rocky Tract', revelationType: 'Meccan', ayahCount: 99 },
    { id: 16, number: 16, nameArabic: 'النَّحۡل', nameEnglish: 'An-Nahl', translation: 'The Bee', revelationType: 'Meccan', ayahCount: 128 },
    { id: 17, number: 17, nameArabic: 'الإِسۡرَاء', nameEnglish: 'Al-Isra', translation: 'The Night Journey', revelationType: 'Meccan', ayahCount: 111 },
    { id: 18, number: 18, nameArabic: 'الكَهۡف', nameEnglish: 'Al-Kahf', translation: 'The Cave', revelationType: 'Meccan', ayahCount: 110 },
    { id: 19, number: 19, nameArabic: 'مَرۡيَم', nameEnglish: 'Maryam', translation: 'Mary', revelationType: 'Meccan', ayahCount: 98 },
    { id: 20, number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', translation: 'Ta-Ha', revelationType: 'Meccan', ayahCount: 135 },
    { id: 21, number: 21, nameArabic: 'الأَنبِيَاء', nameEnglish: 'Al-Anbiya', translation: 'The Prophets', revelationType: 'Meccan', ayahCount: 112 },
    { id: 22, number: 22, nameArabic: 'الحَجّ', nameEnglish: 'Al-Hajj', translation: 'The Pilgrimage', revelationType: 'Medinan', ayahCount: 78 },
    { id: 23, number: 23, nameArabic: 'المُؤۡمِنُون', nameEnglish: 'Al-Muminun', translation: 'The Believers', revelationType: 'Meccan', ayahCount: 118 },
    { id: 24, number: 24, nameArabic: 'النُّور', nameEnglish: 'An-Nur', translation: 'The Light', revelationType: 'Medinan', ayahCount: 64 },
    { id: 25, number: 25, nameArabic: 'الفُرۡقَان', nameEnglish: 'Al-Furqan', translation: 'The Criterion', revelationType: 'Meccan', ayahCount: 77 },
    { id: 26, number: 26, nameArabic: 'الشُّعَرَاء', nameEnglish: 'Ash-Shuara', translation: 'The Poets', revelationType: 'Meccan', ayahCount: 227 },
    { id: 27, number: 27, nameArabic: 'النَّمۡل', nameEnglish: 'An-Naml', translation: 'The Ant', revelationType: 'Meccan', ayahCount: 93 },
    { id: 28, number: 28, nameArabic: 'القَصَص', nameEnglish: 'Al-Qasas', translation: 'The Stories', revelationType: 'Meccan', ayahCount: 88 },
    { id: 29, number: 29, nameArabic: 'العَنكَبُوت', nameEnglish: 'Al-Ankabut', translation: 'The Spider', revelationType: 'Meccan', ayahCount: 69 },
    { id: 30, number: 30, nameArabic: 'الرُّوم', nameEnglish: 'Ar-Rum', translation: 'The Romans', revelationType: 'Meccan', ayahCount: 60 },
    { id: 31, number: 31, nameArabic: 'لُقۡمَان', nameEnglish: 'Luqman', translation: 'Luqman', revelationType: 'Meccan', ayahCount: 34 },
    { id: 32, number: 32, nameArabic: 'السَّجۡدَة', nameEnglish: 'As-Sajda', translation: 'The Prostration', revelationType: 'Meccan', ayahCount: 30 },
    { id: 33, number: 33, nameArabic: 'الأَحۡزَاب', nameEnglish: 'Al-Ahzab', translation: 'The Combined Forces', revelationType: 'Medinan', ayahCount: 73 },
    { id: 34, number: 34, nameArabic: 'سَبَأ', nameEnglish: 'Saba', translation: 'Sheba', revelationType: 'Meccan', ayahCount: 54 },
    { id: 35, number: 35, nameArabic: 'فَاطِر', nameEnglish: 'Fatir', translation: 'The Originator', revelationType: 'Meccan', ayahCount: 45 },
    { id: 36, number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', translation: 'Ya-Sin', revelationType: 'Meccan', ayahCount: 83 },
    { id: 37, number: 37, nameArabic: 'الصَّافَّات', nameEnglish: 'As-Saffat', translation: 'Those Ranges in Ranks', revelationType: 'Meccan', ayahCount: 182 },
    { id: 38, number: 38, nameArabic: 'ص', nameEnglish: 'Sad', translation: 'Sad', revelationType: 'Meccan', ayahCount: 88 },
    { id: 39, number: 39, nameArabic: 'الزُّمَر', nameEnglish: 'Az-Zumar', translation: 'The Groups', revelationType: 'Meccan', ayahCount: 75 },
    { id: 40, number: 40, nameArabic: 'غَافِر', nameEnglish: 'Ghafir', translation: 'The Forgiver', revelationType: 'Meccan', ayahCount: 85 },
    { id: 41, number: 41, nameArabic: 'فُصِّلَتْ', nameEnglish: 'Fussilat', translation: 'Expla ined in Detail', revelationType: 'Meccan', ayahCount: 54 },
    { id: 42, number: 42, nameArabic: 'الشُّورَىٰ', nameEnglish: 'Ash-Shura', translation: 'The Consultation', revelationType: 'Meccan', ayahCount: 53 },
    { id: 43, number: 43, nameArabic: 'الزُّخۡرُف', nameEnglish: 'Az-Zukhruf', translation: 'The Gold Adornments', revelationType: 'Meccan', ayahCount: 89 },
    { id: 44, number: 44, nameArabic: 'الدُّخَان', nameEnglish: 'Ad-Dukhan', translation: 'The Smoke', revelationType: 'Meccan', ayahCount: 59 },
    { id: 45, number: 45, nameArabic: 'الجَاثِيَة', nameEnglish: 'Al-Jathiyah', translation: 'The Kneeling', revelationType: 'Meccan', ayahCount: 37 },
    { id: 46, number: 46, nameArabic: 'الأَحۡقَاف', nameEnglish: 'Al-Ahqaf', translation: 'The Wind-Curved Sandhills', revelationType: 'Meccan', ayahCount: 35 },
    { id: 47, number: 47, nameArabic: 'مُحَمَّد', nameEnglish: 'Muhammad', translation: 'Muhammad', revelationType: 'Medinan', ayahCount: 38 },
    { id: 48, number: 48, nameArabic: 'الفَتۡح', nameEnglish: 'Al-Fath', translation: 'The Victory', revelationType: 'Medinan', ayahCount: 29 },
    { id: 49, number: 49, nameArabic: 'الحُجُرَات', nameEnglish: 'Al-Hujurat', translation: 'The Chambers', revelationType: 'Medinan', ayahCount: 18 },
    { id: 50, number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', translation: 'Qaf', revelationType: 'Meccan', ayahCount: 45 },
    { id: 51, number: 51, nameArabic: 'الذَّارِيَات', nameEnglish: 'Adh-Dhariyat', translation: 'The Scatterers', revelationType: 'Meccan', ayahCount: 60 },
    { id: 52, number: 52, nameArabic: 'الطُّور', nameEnglish: 'At-Tur', translation: 'The Mount', revelationType: 'Meccan', ayahCount: 49 },
    { id: 53, number: 53, nameArabic: 'النَّجۡم', nameEnglish: 'An-Najm', translation: 'The Star', revelationType: 'Meccan', ayahCount: 62 },
    { id: 54, number: 54, nameArabic: 'القَمَر', nameEnglish: 'Al-Qamar', translation: 'The Moon', revelationType: 'Meccan', ayahCount: 55 },
    { id: 55, number: 55, nameArabic: 'الرَّحۡمَن', nameEnglish: 'Ar-Rahman', translation: 'The Most Merciful', revelationType: 'Medinan', ayahCount: 78 },
    { id: 56, number: 56, nameArabic: 'الوَاقِعَة', nameEnglish: 'Al-Waqiah', translation: 'The Event', revelationType: 'Meccan', ayahCount: 96 },
    { id: 57, number: 57, nameArabic: 'الحَدِيد', nameEnglish: 'Al-Hadid', translation: 'The Iron', revelationType: 'Medinan', ayahCount: 29 },
    { id: 58, number: 58, nameArabic: 'المُجَادلَة', nameEnglish: 'Al-Mujadilah', translation: 'The Pleading Woman', revelationType: 'Medinan', ayahCount: 22 },
    { id: 59, number: 59, nameArabic: 'الحَشۡر', nameEnglish: 'Al-Hashr', translation: 'The Gathering', revelationType: 'Medinan', ayahCount: 24 },
    { id: 60, number: 60, nameArabic: 'المُمۡتَحنَة', nameEnglish: 'Al-Mumtahanah', translation: 'The Examined One', revelationType: 'Medinan', ayahCount: 13 },
    { id: 61, number: 61, nameArabic: 'الصَّف', nameEnglish: 'As-Saf', translation: 'The Ranks', revelationType: 'Medinan', ayahCount: 14 },
    { id: 62, number: 62, nameArabic: 'الجُمُعَة', nameEnglish: 'Al-Jumuah', translation: 'The Friday', revelationType: 'Medinan', ayahCount: 11 },
    { id: 63, number: 63, nameArabic: 'المُنَافِقُون', nameEnglish: 'Al-Munafiqun', translation: 'The Hypocrites', revelationType: 'Medinan', ayahCount: 11 },
    { id: 64, number: 64, nameArabic: 'التَّغَابُن', nameEnglish: 'At-Taghabun', translation: 'The Mutual Loss & Gain', revelationType: 'Medinan', ayahCount: 18 },
    { id: 65, number: 65, nameArabic: 'الطَّلَاق', nameEnglish: 'At-Talaq', translation: 'The Divorce', revelationType: 'Medinan', ayahCount: 12 },
    { id: 66, number: 66, nameArabic: 'التَّحۡرِيم', nameEnglish: 'At-Tahrim', translation: 'The Prohibition', revelationType: 'Medinan', ayahCount: 12 },
    { id: 67, number: 67, nameArabic: 'المُلۡك', nameEnglish: 'Al-Mulk', translation: 'The Kingdom', revelationType: 'Meccan', ayahCount: 30 },
    { id: 68, number: 68, nameArabic: 'القَلَم', nameEnglish: 'Al-Qalam', translation: 'The Pen', revelationType: 'Meccan', ayahCount: 52 },
    { id: 69, number: 69, nameArabic: 'الحَاقَّة', nameEnglish: 'Al-Haqqah', translation: 'The Inevitable Reality', revelationType: 'Meccan', ayahCount: 52 },
    { id: 70, number: 70, nameArabic: 'المَعَارِج', nameEnglish: 'Al-Maarij', translation: 'The Ways of Ascent', revelationType: 'Meccan', ayahCount: 44 },
    { id: 71, number: 71, nameArabic: 'نُوح', nameEnglish: 'Nuh', translation: 'Noah', revelationType: 'Meccan', ayahCount: 28 },
    { id: 72, number: 72, nameArabic: 'الجِنّ', nameEnglish: 'Al-Jinn', translation: 'The Jinn', revelationType: 'Meccan', ayahCount: 28 },
    { id: 73, number: 73, nameArabic: 'المُزَّمِّل', nameEnglish: 'Al-Muzzammil', translation: 'The Wrapped in Garments', revelationType: 'Meccan', ayahCount: 20 },
    { id: 74, number: 74, nameArabic: 'المُدَّثِّر', nameEnglish: 'Al-Muddaththir', translation: 'The Cloaked One', revelationType: 'Meccan', ayahCount: 56 },
    { id: 75, number: 75, nameArabic: 'القِيَامَة', nameEnglish: 'Al-Qiyamah', translation: 'The Resurrection', revelationType: 'Meccan', ayahCount: 40 },
    { id: 76, number: 76, nameArabic: 'الإِنسَان', nameEnglish: 'Al-Insan', translation: 'The Human', revelationType: 'Medinan', ayahCount: 31 },
    { id: 77, number: 77, nameArabic: 'المُرۡسَلَات', nameEnglish: 'Al-Mursalat', translation: 'Those Sent Forth', revelationType: 'Meccan', ayahCount: 50 },
    { id: 78, number: 78, nameArabic: 'النَّبَأ', nameEnglish: 'An-Naba', translation: 'The Great News', revelationType: 'Meccan', ayahCount: 40 },
    { id: 79, number: 79, nameArabic: 'النَّازِعَات', nameEnglish: 'An-Naziat', translation: 'Those Who Pull Out', revelationType: 'Meccan', ayahCount: 46 },
    { id: 80, number: 80, nameArabic: 'عَبَسَ', nameEnglish: 'Abasa', translation: 'He Frowned', revelationType: 'Meccan', ayahCount: 42 },
    { id: 81, number: 81, nameArabic: 'التَّكۡوِير', nameEnglish: 'At-Takwir', translation: 'The Overthrowing', revelationType: 'Meccan', ayahCount: 29 },
    { id: 82, number: 82, nameArabic: 'الانفِطَار', nameEnglish: 'Al-Infitar', translation: 'The Cleaving', revelationType: 'Meccan', ayahCount: 19 },
    { id: 83, number: 83, nameArabic: 'المُطَفِّفِينَ', nameEnglish: 'Al-Mutaffifin', translation: 'The Defrauders', revelationType: 'Meccan', ayahCount: 36 },
    { id: 84, number: 84, nameArabic: 'الانشِقَاق', nameEnglish: 'Al-Inshiqaq', translation: 'The Splitting Asunder', revelationType: 'Meccan', ayahCount: 25 },
    { id: 85, number: 85, nameArabic: 'البُرُوج', nameEnglish: 'Al-Buruj', translation: 'The Constellations', revelationType: 'Meccan', ayahCount: 22 },
    { id: 86, number: 86, nameArabic: 'الطَّارِق', nameEnglish: 'At-Tariq', translation: 'The Morning Star', revelationType: 'Meccan', ayahCount: 17 },
    { id: 87, number: 87, nameArabic: 'الأَعۡلَىٰ', nameEnglish: 'Al-Ala', translation: 'The Most High', revelationType: 'Meccan', ayahCount: 19 },
    { id: 88, number: 88, nameArabic: 'الغَاشِيَة', nameEnglish: 'Al-Ghashiyah', translation: 'The Overwhelming Event', revelationType: 'Meccan', ayahCount: 26 },
    { id: 89, number: 89, nameArabic: 'الفَجۡر', nameEnglish: 'Al-Fajr', translation: 'The Dawn', revelationType: 'Meccan', ayahCount: 30 },
    { id: 90, number: 90, nameArabic: 'البَلَد', nameEnglish: 'Al-Balad', translation: 'The City', revelationType: 'Meccan', ayahCount: 20 },
    { id: 91, number: 91, nameArabic: 'الشَّمۡس', nameEnglish: 'Ash-Shams', translation: 'The Sun', revelationType: 'Meccan', ayahCount: 15 },
    { id: 92, number: 92, nameArabic: 'اللَّيۡل', nameEnglish: 'Al-Layl', translation: 'The Night', revelationType: 'Meccan', ayahCount: 21 },
    { id: 93, number: 93, nameArabic: 'الضُّحَىٰ', nameEnglish: 'Ad-Duha', translation: 'The Forenoon', revelationType: 'Meccan', ayahCount: 11 },
    { id: 94, number: 94, nameArabic: 'الشَّرۡح', nameEnglish: 'Ash-Sharh', translation: 'The Opening Forth', revelationType: 'Meccan', ayahCount: 8 },
    { id: 95, number: 95, nameArabic: 'التِّين', nameEnglish: 'At-Tin', translation: 'The Fig', revelationType: 'Meccan', ayahCount: 8 },
    { id: 96, number: 96, nameArabic: 'العَلَق', nameEnglish: 'Al-Alaq', translation: 'The Clot', revelationType: 'Meccan', ayahCount: 19 },
    { id: 97, number: 97, nameArabic: 'القَدۡر', nameEnglish: 'Al-Qadr', translation: 'The Night of Decree', revelationType: 'Meccan', ayahCount: 5 },
    { id: 98, number: 98, nameArabic: 'البَيِّنَة', nameEnglish: 'Al-Bayyinah', translation: 'The Clear Evidence', revelationType: 'Medinan', ayahCount: 8 },
    { id: 99, number: 99, nameArabic: 'الزِّلۡزَال', nameEnglish: 'Az-Zalzalah', translation: 'The Earthquake', revelationType: 'Medinan', ayahCount: 8 },
    { id: 100, number: 100, nameArabic: 'العَادِيَات', nameEnglish: 'Al-Adiyat', translation: 'The Courser', revelationType: 'Meccan', ayahCount: 11 },
    { id: 101, number: 101, nameArabic: 'القَارِعَة', nameEnglish: 'Al-Qariah', translation: 'The Striking Hour', revelationType: 'Meccan', ayahCount: 11 },
    { id: 102, number: 102, nameArabic: 'التَّكَاثُر', nameEnglish: 'At-Takathur', translation: 'The Piling Up', revelationType: 'Meccan', ayahCount: 8 },
    { id: 103, number: 103, nameArabic: 'العَصۡر', nameEnglish: 'Al-Asr', translation: 'The Time', revelationType: 'Meccan', ayahCount: 3 },
    { id: 104, number: 104, nameArabic: 'الهُمَزَة', nameEnglish: 'Al-Humazah', translation: 'The Slanderer', revelationType: 'Meccan', ayahCount: 9 },
    { id: 105, number: 105, nameArabic: 'الفِيل', nameEnglish: 'Al-Fil', translation: 'The Elephant', revelationType: 'Meccan', ayahCount: 5 },
    { id: 106, number: 106, nameArabic: 'قُرَيۡش', nameEnglish: 'Quraysh', translation: 'Quraysh', revelationType: 'Meccan', ayahCount: 4 },
    { id: 107, number: 107, nameArabic: 'المَاعُون', nameEnglish: 'Al-Maun', translation: 'The Small Kindnesses', revelationType: 'Meccan', ayahCount: 7 },
    { id: 108, number: 108, nameArabic: 'الكَوۡثَر', nameEnglish: 'Al-Kawthar', translation: 'The Abundance', revelationType: 'Meccan', ayahCount: 3 },
    { id: 109, number: 109, nameArabic: 'الكَافِرُون', nameEnglish: 'Al-Kafirun', translation: 'The Disbelievers', revelationType: 'Meccan', ayahCount: 6 },
    { id: 110, number: 110, nameArabic: 'النَّصۡر', nameEnglish: 'An-Nasr', translation: 'The Help', revelationType: 'Medinan', ayahCount: 3 },
    { id: 111, number: 111, nameArabic: 'المَسَد', nameEnglish: 'Al-Masad', translation: 'The Palm Fiber', revelationType: 'Meccan', ayahCount: 5 },
    { id: 112, number: 112, nameArabic: 'الإِخۡلَاص', nameEnglish: 'Al-Ikhlas', translation: 'The Sincerity', revelationType: 'Meccan', ayahCount: 4 },
    { id: 113, number: 113, nameArabic: 'الفَلَق', nameEnglish: 'Al-Falaq', translation: 'The Daybreak', revelationType: 'Meccan', ayahCount: 5 },
    { id: 114, number: 114, nameArabic: 'النَّاس', nameEnglish: 'An-Nas', translation: 'Mankind', revelationType: 'Meccan', ayahCount: 6 }
]

// Helper functions
export const getSurahById = (id) => {
    return MOCK_SURAHS.find(surah => surah.id === parseInt(id))
}

export const searchSurahs = (query) => {
    if (!query) return MOCK_SURAHS

    const lowerQuery = query.toLowerCase()
    return MOCK_SURAHS.filter(surah =>
        surah.nameEnglish.toLowerCase().includes(lowerQuery) ||
        surah.nameArabic.includes(query) ||
        surah.translation.toLowerCase().includes(lowerQuery) ||
        surah.number.toString() === query
    )
}

export default MOCK_SURAHS
